### ISSUE TITLE
Control only fingers with angular/cartesian command

### ISSUE THREAD

**Issue by mathijsdelangen** [RIVeR-Lab/wpi_jaco#15]
The angular/cartesian command does not work for only the fingers:

I have used the topic jaco_arm/angular_cmd (or jaco_arm/cartesian_cmd,
they have the same issue) to send a angular command to just the fingers
to move the gripper. As an example, I had sent the following command via
the terminal:

    rostopic pub /jaco_arm/angular_cmd wpi_jaco_msgs/AngularCommand
    "position: true
    armCommand: false
    fingerCommand: true
    repeat: true
    joints: [-1.4125960359287015, 2.975129639125518, 0.866657599842382,
    -2.3226120288464456, 1.6268935514704892, 1.4014925183958342,
    -0.004363323129985824, -0.004363323129985824, -0.004363323129985824]
    fingers: [0, 0, 0]"

The fingers did not move at all for any value I had put in. When I
switched armCommand to true (the joint values are the current joint
values of the arm), the fingers did open.

**Comment by dekent** [comment]
It looks like the API only allows finger position commands to be sent if an arm position command is sent with it.  Previously if you were sending only a finger command the callback would automatically fill in a 0 joint velocity command, but the API will only accept a position finger command if a position arm command is set.  For now I changed it so that if you don't specify an arm joint command and you're trying to send a finger position command, it will automatically fill in the current arm positions to send in the API command.

There's some error in the joint position accuracy (at least in our arm), so the arm jerks a bit when you send only a finger position command.  The velocity command works fine, however, as sending a 0 velocity with finger velocities gives the desired behavior.  I think a better solution would be to write a PID controller that will use finger velocity commands to reach a desired finger position, so that the arm can be held in place with a 0 velocity command instead of the current position command.  I'll look into that in the near future!

**Comment by dekent** [comment]
I implemented the PID controller instead, now it works pretty nicely!

**Comment by mathijsdelangen** [comment]
Also my tests show nice results!
