### ISSUE TITLE
NO_DEVICE using wpi_jaco_wrapper with MICO

### ISSUE THREAD

**Issue by mara172** [RIVeR-Lab/wpi_jaco#32]
I had installed and compiled all files of wpi_jaco correctly. And starting the "roslaunch wpi_jaco_wrapper arm.launch arm_name:=mico" . The jaco_arm_trajectory-node is executing all till reaching the MoveHome-Funktion. There, the robot is moving to the home position but afterwards the console sends NO_DEVICE and the script is hanging... What could I do to solve the Problem?

Thanks for your help!

![mico](https://cloud.githubusercontent.com/assets/11994831/7203537/99c0ae74-e51b-11e4-946a-6d749ec9c0d8.png)

**Comment by dekent** [comment]
Did you clone the latest code from this repository or did you install it with apt (sudo apt-get install ...)?  We had this problem when using a different version of the kinova sdk, which has since been reverted in the repository.  There was some lag before it was released, however, so you may still have the version that causes this error.

Try cloning the repository into your catkin workspace again, remove your build, devel, and install folders, and rebuild everything.  Let me know if you still get the error and we'll go from there.

**Comment by mathijsdelangen** [comment]
Indeed. I had the same problem with the Mico arm. The old libraries - as @dekent just described - helped me with this issue.

**Comment by mara172** [comment]
Now I deleted all old/ new versions of the KinovaSDK and  the repository wpi-jaco. I cloned the repository again. Again compiling all is fine... But now I get the Error "Could not initialize Kinova API. Is the arm connected?" And the Arm isn't moving anymore. Do I need some additional packages?

**Comment by mathijsdelangen** [comment]
Additional packages are not needed, that I know. 

Could you do a 
```bash
locate "Kinova.API"
```

on your system?  Maybe you have some libraries still somewhere.

**Comment by mara172** [comment]
Fist of all I forget: Thank you for your help!!!
I've written locate "Kinove.API" and there are existing only libraries of Kinova in my catkin-workspace.
The problem is still the same.

**Comment by mathijsdelangen** [comment]
I think I would need a clean installation to try and reproduce this. I will get back to you later today I guess.

**Comment by mathijsdelangen** [comment]
Possibily, I know where the problem lies. I noticed on my system that I have a Kinova library installed in the following directories: 
/usr/include/Kinova.API.CommLayerUbuntu.h
/usr/include/Kinova.API.UsbCommandLayerUbuntu.h
/usr/lib/Kinova.API.CommLayerUbuntu.so
/usr/lib/Kinova.API.USBCommandLayerUbuntu.so

Could it be possible something goes wrong when linking the libraries in the jaco_sdk folder, @dekent? With the Jaco you have no issue I guess.

As a quick fix, I could send you the installation files, @mara172, to install these libraries on your system. Drop me an email if you would like that.

I will take a look into the problem.

**Comment by dekent** [comment]
It does sound like something's going wrong with the installation.  I'll try a clean install as well to see what's going on.  It also doesn't sound like it should be a mico only problem.  Thanks for the feedback!

**Comment by mathijsdelangen** [comment]
To clarify the issue: Installing KinovaAPI-5.0.6-amd64.deb on a Ubuntu machine did work on the machine of @mara172 and also on mine and another machine here in my office. 

I guess the installation goes wrong indeed. Not sure if it is only a problem for the Mico, so let me know what a clean install does for you.

**Comment by dekent** [comment]
I'm having the same problem doing a clean install on another machine in my lab, running Ubuntu 14.04.  I should have time to look into this in more detail tomorrow!
