### ISSUE TITLE
Cannot initialize Kinova API on Mico arm

### ISSUE THREAD

**Issue by cbod** [RIVeR-Lab/wpi_jaco#33]
Hi,

I've been trying to get wpi_jaco running, but I cannot get the API to communicate with the arm. I've tried both the master and dev branches and have the correct udev rules, but still no luck:

![wpi_cannot_connect](https://cloud.githubusercontent.com/assets/10853348/7309050/f7fb08e0-e9df-11e4-806f-ac66ac86781c.png)

Interestingly, I can connect if I use the jaco_ros package from Kinova:

![jaco_ros_working](https://cloud.githubusercontent.com/assets/10853348/7309063/145b4694-e9e0-11e4-8977-9777f78fbc3e.png)

Any help would be great, thank you!

Chris

**Comment by mathijsdelangen** [comment]
Hi Chris, 

I think this is a similar problem to #32, right?

**Comment by dekent** [comment]
It does look like the same problem.  Something's going wrong with the library installation, and I'm still trying to figure out what it is, but for now can you try installing the Kinova API with the .deb that Kinova includes with the arm?

**Comment by cbod** [comment]
I had read #32, but wasn't completely sure if they were the same since I could run the jaco_ros package from Kinova. Thank you for the suggestion! I'll give the .deb a shot when I get into the lab.

**Comment by cbod** [comment]
Using the Kinova API with the .deb solved the issue. Thanks very much!

**Comment by patzaa** [comment]
Hello,
right now I have the same problem as you @cbod previously got.
Could you pleas explain how you solved the issue exactly, i don't understand the .deb thing 
Thank you very much!

**Comment by dekent** [comment]
Hi Patzaa,

On some machines, the libraries found in the jaco_sdk package aren't being installed correctly.  I haven't been able to figure out why this is happening because I haven't been able to replicate the problem on my own machine, but I can explain the .deb thing.

What you should try first is manually installing the KinovaAPI-5.0.6-amd64.deb file which should have come with Kinova's software that comes with the arm (API/Ubuntu/[32 or 64]Bits/KinovaAPI-5.0.6-amd64.deb).

Alternatively, you can manually copy the two library files to your , libKinova.API.CommLayerUbuntu.so and libKinova.API.USBCommandLayerUbuntu.so, found in the lib directory of the jaco_sdk package to your /usb/lib directory.

Kinova also has some updated API files which you can get from the kinova-ros repository here: https://github.com/Kinovarobotics/kinova-ros/tree/master/jaco_driver/lib.  You can try these as well, but if I remember correctly they were breaking something with our driver... I can't confirm this at the moment though, and I'm wary of making changes to the repository here because I currently don't have access to a JACO for testing.

Let me know if you have any questions!

**Comment by patzaa** [comment]
Thank you very much for you help! 
fist of all I installed the KinovaAPI-5.0.6-amd64.deb with 
$sudo dpkg -i KinovaAPI-5.0.6-amd64.deb
$sudo apt-get -f install  

and now everything is working fine!

**Comment by Behery** [comment]
Hi guys, I seem to be having the same problem 3 years later :/ 
But I don't have the `KinovaAPI-5.0.6-amd64.deb` that came with the arm. I tried what @dekent mentioned above, 

> Alternatively, you can manually copy the two library files to your , libKinova.API.CommLayerUbuntu.so and libKinova.API.USBCommandLayerUbuntu.so, found in the lib directory of the jaco_sdk package to your /usb/lib directory.

but I'm still having the same problem 
Is there anywhere I can find the deb files online? the kinova-ros repository is working for me and communicating with the arm, but I wanted to use this repository for the keyboard and joystick teleop nodes. 

Thanks :)

**Comment by dekent** [comment]
This might not work with new versions of the arm anymore... We moved over to kinova-ros as well, as it's been significantly updated since we originally made this repo, so I haven't tested the libraries included in this package for a while.  The kinova-ros package does have libraries [here](https://github.com/Kinovarobotics/kinova-ros/tree/master/kinova_driver/lib) that might work, but again I can't vouch for the package anymore.

I wouldn't mind having the keyboard and joystick teleop working again, though, so if I have some free time I'll update them to work with kinova-ros and release them in a new package.  If I get that done, I'll post a comment here!

**Comment by Behery** [comment]
Thanks ... I'll give it a try then :) 

also thanks for the quick reply @dekent !!
