### ISSUE TITLE
Mico - Moveit - joint_states/ grippercontroller mismatch

### ISSUE THREAD

**Issue by raphimulator** [RIVeR-Lab/wpi_jaco#34]
Hi,
I've made a moveit config for our Kinova Mico, based on wpi_jaco. It works far better than other repositories btw.
Now I've come across this problem:

When I use /mico_arm/fingers_controller/gripper as GripperCommand, it won't execute grasp movements corrently. I think this is based on the fact that the action-goal accept values from 0.0 to ~7000.0 for open and closed finger position, while joint_states are published in radians from ~0.0 to ~1.0.

So when moveit tries to close both fingers, Mico goes to fully open position, since for /mico_arm/fingers_controller/gripper/goal the value 1.0 means open, in whatever unit that is.

**Comment by dekent** [comment]
I haven't used MoveIt! to control the gripper, but what you're saying makes sense if MoveIt! controls the gripper based on the joint_state position.  If that's the case I can make a moveit-friendly gripper controller that converts a joint state position goal into the units that the Kinova API uses.

Do you have the exact value that moveit's sending for a close command?  It's hard for me to test because I only have a Jaco, but aside from the scale the principle should be the same.

**Comment by raphimulator** [comment]
Alright! That would be amazing.

I manually sent positions to the GripperCommand using axclient.py. Then I read the /joint_states topic and made a small table:

| Request	| Measured Joint State	| Ratio
| 10.0       | 0.001745329251296198| 5729.6
| 100.0 	| 0.013962634010369583| 7162.0
| 1000.0	| 0.1448623278575844	| 6903.1
| 2000.0 	| 0.29146998496646503	| 6861.8
| 4000.0 	| 0.5811946406816338	| 6882.4
| 5000.0 	| 0.7278022977905144	| 6870.0
| 7000.0 	| 1.0175269535056835	| 6879.4

It's hard to tell the exact mutliplicator, but I'd say the GripperCommand's position must be about 6900 times bigger than the joint_state's radian.

**Comment by dekent** [comment]
Alright, update to the latest code in the develop branch and give it a try.  Just have your MoveIt! config use /mico_arm/fingers_controller_radian/gripper as the gripper action server instead.  It might not be tuned exactly right, but it works for my gripper open/close values on the Jaco.  Let me know how it works for you!

**Comment by raphimulator** [comment]
Great job! It works fine.

Thanks for the support
