### ISSUE TITLE
Cartesian topic being blocked 

### ISSUE THREAD

**Issue by raphimulator** [RIVeR-Lab/wpi_jaco#37]
Maybe this is a pure MoveIt related problem, but we noticed that when using a node that uses moveit::planning_interface::MoveGroup, the jaco_arm/cartesian_cmd  won't work anymore, while jaco_arm/angular_cmd works fine.
Most solutions we found suggested using asyncspinners, but that didn't solve it.

Sorry if this is only MoveIt related, but we are trying to eliminate all sources of error, while having much time pressure.
In that case, just  close or remove this topic.

**Comment by raphimulator** [comment]
today we suffered the same problem, after using jaco_arm/angular_cmd for a couple of times, while no MoveIt was running.

**Comment by raphimulator** [comment]
We noticed that we can restart jaco_arm_trajectory_node to reanable cartesian control, eventhough MoveIt runs in parallel.
Sadly this strategy doesn't work, when homing is disabled.

**Comment by Cinematics** [comment]
Hi,

same problem here...
We are using a Mico arm + MoveIt! (mico_arm/angular_cmd) and a joypad control mode (mico_arm/cartesian_cmd). After a movement via MoveIt! (over mico_arm/angular_cmd) the cartesian topic is sometimes blocked/ignored and sometimes not. As far as I know, this depends on the current pose/joint configuration of the robot. The topic is always blocked in some poses and in other its always working ... maybe because the arm is moved into a configuration, which can't be reached via cartesian movement and further cartesian movement is therefore blocked (out of bounds?!) 

Furthermore this seems not to be a problem of the wpi_jaco package, because the original [Kinova ROS Package] (https://github.com/Kinovarobotics/kinova-ros#known-limitations) declares the following limitation:
*After using angular control, the arm may not respond to Cartesian commands (e.g., arm_pose or figer_position) until the arm has been homed.*

So it seems to be a Kinova Software Bug/Limitation and can't be fixed unfortunately...

**Comment by dekent** [comment]
Yeah, as far as I've been able to figure out, this is a problem with Kinova's API.  Both this package and the kinova-ros packages use the same API to communicate with the arm at a low level.  The arm has defined zones to avoid due to singularities while it's operating in Cartesian control mode.  They are reachable with angular control, however, and the arm won't respond if you move into one of these spaces and switch to Cartesian control.  Homing the arm will fix this, as it moves the arm back into a valid pose.

It's also possible to use angular control to move to another non-singularity pose and resume Cartesian control.  I'm not sure how to detect what poses are safe for Cartesian control.  We try to do as much with angular control as possible to avoid this problem (you can also use MoveIt! to plan cartesian trajectories, and execute them as angular trajectories on the arm).  Unfortunately I'm not sure if there's a solution.  I see it as a limitation, as you suggest.
